#!/usr/bin/env python2.7

### DIRECTORIES
## temporary dirs' folder
# default: /tmp
TMP_FOLDER = "/tmp"

# numpy memmap folder
# default: /dev/shm
NUMPY_MEMMAP_DIR = "/dev/shm"

### NUMBER OF SEQUENCES IN A VOLUME
VOL_SIZE = 500

### CLUSTERING THRESHOLD
# default: 10
THRESHOLD = 10

### MAXIMUM FRACTION OF REMOVED COLUMNS
DYHOLD = 0.25

### NUMBER OF NON_REDUNDANT SEQUENCES WHERE IT SWITCHES TO KEEP ONLY "CLEAN" COLUMNS
PHOLD = 100

### MINIMUM KNOWN BASES PER COLUMN IN SEQUENCE MATRIX
CLEAN = 0.90
